apiVersion: v1
kind: Service
metadata:
  name: {{ include "talea-worker.fullname" . }}
  labels:
    {{- include "talea-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.worker.serviceType }}
  selector:
    app.kubernetes.io/name: {{ include "talea-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: bootstrap
      port: {{ .Values.worker.bootstrapPort }}
      targetPort: bootstrap
    - name: sglang
      port: {{ .Values.worker.servicePort }}
      targetPort: sglang
    - name: pd-bootstrap
      port: {{ .Values.worker.prefillBootstrapPort }}
      targetPort: pd-bootstrap
